### PR TITLE
Remove null, undefined, empty array, and empty object fields

### PR DESCRIPTION
**Pull request by TheConnMan**
There are no functional changes in this commit, only field removal and whitespace changes.

### CODE REVIEW

**Review by rclagett — APPROVED** [review]

**Review by Grumblesmith — APPROVED** [review]

**Comment by TheConnMan** [comment]
I think I'd still like to remove the empty fields on these packages, especially because the Metricly CLI won't construct the null fields when dealing with packages. Thoughts? I think we held up on this PR because not everyone agreed on removing them.

**Comment by bspindler** [comment]
I’m good removing them.

**Comment by TheConnMan** [comment]
I've updated this using the new Metricly CLI formatter (https://github.com/metricly/metricly-cli/pull/55). If everything looks good on this PR then I'll roll the formatter through all the other packages.

**Comment by rclagett** [comment]
Have you provisioned this version of the package to a tenant and confirmed it still works as expected? Removal of things like the ACS config types make me nervous

**Comment by Grumblesmith** [comment]
Shouldn't be removed, just reorganized to the bottom of the file.

**Comment by TheConnMan** [comment]
@rclagett I provisioned an EC2 package to an account and checked out all the dashboards. I'll check today to see how the computed metrics and ACS configs are doing.

**Comment by TheConnMan** [comment]
Computed metrics still look good for EC2s today.

**Comment by rclagett** [comment]
Cool. My approval stands.

**Pull request merged**
